"""updated post1

Revision ID: 24b9cbf00105
Revises: 583e8bb34dfe
Create Date: 2019-10-05 13:55:00.441700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24b9cbf00105'
down_revision = '583e8bb34dfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aquarium') as batch_op:
        batch_op.drop_column('temperature')
        batch_op.drop_column('ph')
    #op.drop_column('aquarium', 'temperature')
    #op.drop_column('aquarium', 'ph')
    op.add_column('post', sa.Column('image_filename', sa.String(), nullable=True))
    op.add_column('post', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'image_url')
    op.drop_column('post', 'image_filename')
    op.add_column('aquarium', sa.Column('ph', sa.INTEGER(), nullable=True))
    op.add_column('aquarium', sa.Column('temperature', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
