"""empty message

Revision ID: 536cb9080a94
Revises: 24b9cbf00105
Create Date: 2019-10-15 18:37:56.735733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '536cb9080a94'
down_revision = '24b9cbf00105'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aquarium', sa.Column('image_filename', sa.String(), nullable=True))
    op.add_column('aquarium', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('aquarium', 'image_url')
    op.drop_column('aquarium', 'image_filename')
    # ### end Alembic commands ###
