"""added data table

Revision ID: 5d38427057c7
Revises: 8ee6c89e492a
Create Date: 2019-09-01 16:25:21.720634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d38427057c7'
down_revision = '8ee6c89e492a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aquarium_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('temperature', sa.Integer(), nullable=True),
    sa.Column('ph', sa.Integer(), nullable=True),
    sa.Column('aquarium_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aquarium_id'], ['aquarium.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aquarium_data_timestamp'), 'aquarium_data', ['timestamp'], unique=False)
    op.drop_column('aquarium', 'temperature')
    op.drop_column('aquarium', 'ph')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aquarium', sa.Column('ph', sa.INTEGER(), nullable=True))
    op.add_column('aquarium', sa.Column('temperature', sa.INTEGER(), nullable=True))
    op.drop_index(op.f('ix_aquarium_data_timestamp'), table_name='aquarium_data')
    op.drop_table('aquarium_data')
    # ### end Alembic commands ###
